"""initial migration

Revision ID: 173bd1436f77
Revises: 
Create Date: 2017-12-04 10:01:37.995521

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '173bd1436f77'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adminlog', sa.Column('admin_id', sa.Integer(), nullable=True))
    op.drop_constraint('adminlog_ibfk_1', 'adminlog', type_='foreignkey')
    op.create_foreign_key(None, 'adminlog', 'admin', ['admin_id'], ['id'])
    op.drop_column('adminlog', 'user_id')
    op.add_column('oplog', sa.Column('admin_id', sa.Integer(), nullable=True))
    op.drop_constraint('oplog_ibfk_1', 'oplog', type_='foreignkey')
    op.create_foreign_key(None, 'oplog', 'admin', ['admin_id'], ['id'])
    op.drop_column('oplog', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oplog', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'oplog', type_='foreignkey')
    op.create_foreign_key('oplog_ibfk_1', 'oplog', 'admin', ['user_id'], ['id'])
    op.drop_column('oplog', 'admin_id')
    op.add_column('adminlog', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'adminlog', type_='foreignkey')
    op.create_foreign_key('adminlog_ibfk_1', 'adminlog', 'admin', ['user_id'], ['id'])
    op.drop_column('adminlog', 'admin_id')
    # ### end Alembic commands ###
